version: "3.0.4"

networks:
  local-dhcp:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/24
          gateway: 172.5.0.1

services:
  gns3-server:
    image: jsimonetti/gns3-server:3.0.4
    privileged: true
    networks:
      - local-dhcp
    ports:
      - "3080:3080" # API Port
      - "5000-5050:5000-5050" # For Telnet
    volumes:
      - ./data:/root/GNS3
    depends_on:
      - dhcp-server

  dhcp-server:
    image: networkboot/dhcpd:1.3.0
    networks:
      - local-dhcp
    init: true
    command: eth0
    volumes:
      - ./dhcp-config:/data