version: "3.0.4"
services:
  gns3:
    image: jsimonetti/gns3-server:3.0.4
    container_name: gns3-server
    privileged: true
    ports:
      - 3080:3080
      - 8080:80
      - 443:443
    volumes:
      - gns3_data:/root/GNS3
      - /lib/modules:/lib/modules:ro
    environment:
    restart: unless-stopped
    networks:
      - gns3net
volumes:
  gns3_data:
networks:
  gns3net:
    driver: bridge