version: "3.9"

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.11.2
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_manager_data:/var/ossec/data

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.11.2
    restart: unless-stopped
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${APP_PASSWORD:-admin}"
      - "DISCOVERY_TYPE=single-node"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - wazuh_indexer_data:/usr/share/opensearch/data

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.11.2
    restart: unless-stopped
    depends_on:
      - wazuh-indexer
    environment:
      - DASHBOARD_PASSWORD=${APP_PASSWORD:-admin}
      - OPENSEARCH_HOSTS=https://wazuh-indexer:9200
    ports:
      - "5601:5601"

volumes:
  wazuh_manager_data:
  wazuh_indexer_data:
