version: "4.11.2"

services:

  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml

  wazuh-manager:
    image: wazuh/wazuh-manager:4.11.2
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_manager_data:/var/ossec/data
      - ./config/certs/wazuh-manager:/var/ossec/certs

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.11.2
    restart: unless-stopped
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${APP_PASSWORD:-admin}"
      - "DISCOVERY_TYPE=single-node"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - wazuh_indexer_data:/usr/share/opensearch/data
      - ./config/certs/wazuh-indexer:/usr/share/opensearch/config/certs

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.11.2
    restart: unless-stopped
    depends_on:
      - wazuh-indexer
    environment:
      - DASHBOARD_PASSWORD=${APP_PASSWORD:-admin}
      - OPENSEARCH_HOSTS=https://wazuh-indexer:9200
    ports:
      - "5601:5601"
    volumes:
      - ./config/certs/wazuh-dashboard:/usr/share/wazuh-dashboard/config/certs

volumes:
  wazuh_manager_data:
  wazuh_indexer_data:
